/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __DEFINE_H
#define __DEFINE_H

/* Includes ------------------------------------------------------------------*/
#include "stm8l15x.h"

#define BACK 0x01
#define REPEAT 0x02
#define ID 0x01
#define USER 0x01
#define MANAGER 0x02
#define END_FRAME 0xEF
#define SIZEOFFRAME 16
#define REFRESH 350


#define REGISTER_USER 0
#define DELETE_USER 2
#define INSTALL_SYSTEM 4
#define INTRUDUCTION_EQUIPMENT 6
#define AND_FINGERPRINT 8
#define AND_PASSWORD 10
#define AND_CARD 12
#define REMOVE_ONE_FINGERPRINT 16
#define REMOVE_ONE_PASSWORD 18
#define REMOVE_ONE_CARD 20
#define REMOVE_ALL_FINGERPRINT 24
#define REMOVE_ALL_PASSWORD 26
#define REMOVE_ALL_CARD 28
#define ADJ_SOUND 32
#define SETTING_LANGUAGE 34
#define SYSTEM_RECOVERY 36
#define SETTING_NETWORK 38
#define NOTIFICATION_MANAGER 44
#define NOTIFICATION_USER 46
#define WARING_CRACK 48
#define TEMPORARY_USER 50
#define MAX_SOUND 52
#define MIND_SOUND 54
#define MIN_SOUND 56
#define CLAM_SOUND 58
#define PRODUCT_INFORMATION 60
#define FORMAT_SYSTEM 66
#define VERIFY_SUCCESSFUL 70
#define VERIFY_NOT_SUCCESSFUL 72
#define OPERATION_SUCCESSFUL 74
#define OPERATION_NOT_SUCCESSFUL 76
#define USER_ALREADY_EXISTS 78
#define USER_ALREADY_FULL 80
#define SUGGEST_PLACING_FINGERPRINT 82
#define SUGGEST_SCANING_CARD 84
#define SUGGEST_ENTER_NEW_PASSWORD 86
#define SUGGEST_ENTER_NEW_PASSWORD_AGAIN 88
#define SUGGEST_ENTER_USER_ORDER_NUMBER 92
#define USER_ORDER_NUMBER 96
#define TO_CONFIRM_PRESS_THANG 98
#define TO_BACK_PRESS_SAO 100
#define KEYBOARD_IS_LOCKED 102
#define LOW_BATTERY_WARNING 104
#define VIETNAMESE 106
#define ENGLISH 107
#define HAS_MOVED_TO_FIXED_STATE 108
#define HAS_REMOVE_MOVED_TO_FIXED_STATE 110
#define PRESS_THANG_KEY_TO_ENTER_SETTING_LIST 112
#define SUGGEST_SETTING_MANAGER 118
#define PRESS_KEY 120
#define SPEAK_0 122
#define SPEAK_1 124
#define SPEAK_2 126
#define SPEAK_3 128
#define SPEAK_4 130
#define SPEAK_5 132
#define SPEAK_6 134
#define SPEAK_7 136
#define SPEAK_8 138
#define SPEAK_9 140
#define INSIDE_LOCKED_DOOR 142
#define SYSTEM_HAS_EXITED 146
#define FINGERPRINT_WAS_USED 148
#define CARD_WAS_USED 150
#define PASSWORD_WAS_USED 152
#define USE_LOCK_LEFT 154
#define UNUSER_LOCK_LEFT 156
#define SETTING_LOCK_LEFT 158
#define SUCCESSFULLY_RECOVERY_SYSTEM 160
#define PASSWORD_WAS_FULL 164
#define FINGERPRINT_WAS_FULL 166
#define CARD_WAS_FALL 168
#define LISTEN_AGAIN_PRESS_THANG 178
#define NUMBER_BOARD 180
#define MACHINE_CODE 182
#define PLEASE_RESET_FINGERPRINT 186
#define AND_NETWORK 189
#define SUCCESSFULLLY_NETWORK 191
#define USE_SOLID_FINGER_AT_DIFFERENT_ANGLES 192
#define CHANGE_ANGLE_FINGERPRINT 196
#define SOUND_WHEN_TOUCHING_KEYBOARD_FIRST_TIME 200
#define SOUND_WHEN_PRESS_NUMBER 201
#define SOUND_WHEN_TURN_SWITCH 206
#define SOUND_WHEN_WANING 205
#define SOUND_WHEN_PRESS_BELL 208
#define BIG_SOUND 231
#define NORMAL_SOUND 227
#define NOT_SOUND 224 

#define MAX_TIME_SOUND 4000
#define MID_TIME_SOUND 3000
#define MID_MIN_TIME_SOUND 2500
#define NORMAL_TIME_SOUND 2000
#define MID_MIN_MIN_TIME_SOUND 1500
#define MIN_TIME_SOUND 1000


#endif //__DEFINE_H 